sudo: require
services:
  - docker
before_install:
  - docker build

language: python
python:
  - "3.7"


env:
  global:
    - BUILD_ON_TRAVIS=true

before_script: pip install docker-compose

script:
  - docker-compose run --rm app sh -c "python manage.py test"
