sudo: require
services:
  - docker
language: python
python:
  - "3.7"
env:
  global:
    - BUILD_ON_TRAVIS=true
before_install:
  - docker build -t lukaszmalucha/docker-django .
script:
  - docker run lukaszmalucha/docker-django python manage.py test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push lukaszmalucha/docker-django